### ISSUE TITLE
Sign Up Form: Section " Where I want to be in 5 Years " 

### ISSUE THREAD

**Issue by BigSuave** [teambangbang/www#20]
When sign up section for “ where I wanna be in 5years " is in focus words should disappear on focus or user should be able to select all and delete.
![image](https://cloud.githubusercontent.com/assets/8550737/9953283/37d255b8-5d94-11e5-96c0-dc3e7a7550c3.png)

**Comment by vicmaster** [comment]
If you ask me about this, I rather disappear after focus than let the user erase all the text because this is just an example... what do you think?

**Comment by BigSuave** [comment]
Let's have it disappear after focus.

**Comment by vicmaster** [comment]
Right now is the way it is... so should I close this issue?

**Comment by vicmaster** [comment]
I see what you mean, working on it!

**Comment by vicmaster** [comment]
https://github.com/teambangbang/www/pull/28
