### ISSUE TITLE
Hashtage & Action signs

### ISSUE THREAD

**Issue by BigSuave** [teambangbang/www#21]
If you try and type an action !! or hashtag # and delete a letter and try and correct the tag by adding the word back, the tag doesn't recognize the word as being apart of the tag.
![image](https://cloud.githubusercontent.com/assets/8550737/9953382/1715f374-5d95-11e5-8038-201f2bdb5d91.png)

**Comment by vicmaster** [comment]
When you have some time please check this on staging :facepunch:
