### ISSUE TITLE
Welcome text after signing up/logging in

### ISSUE THREAD

**Issue by BigSuave** [teambangbang/www#25]
"Welcome! You have signed in successfully" text should be centered to profile div.
![image](https://cloud.githubusercontent.com/assets/8550737/9953527/645be69c-5d96-11e5-8c64-b5438673cac1.png)

**Comment by vicmaster** [comment]
https://www.evernote.com/l/AReXe9ieDPVFmZK5MKGnVvavMxKApfJsS3AB/image.png

**Comment by vicmaster** [comment]
I can reproduce this one because looks already centered, did you tested this on a big screen or something like that?

**Comment by vicmaster** [comment]
I believe I need to learn to read haha, I just found you want this be centered on profile div, lol, working on it!
